@startuml
class AudioSO {
    + Name : string <<get>>
    + Volume : float <<get>>
    + Pitch : float <<get>>
    + IsLoop : bool <<get>>
}
ScriptableObject <|-- AudioSO
AudioSO --> "Clip" AudioClip
AudioSO --> "Source" AudioSource
@enduml
